# -*- mode:python -*-

# Copyright (c) 2009 The Hewlett-Packard Development Company
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Authors: Nathan Binkert

Import('*')

if env['PROTOCOL'] == 'None':
    Return()

DebugFlag('RubyVOQ_VA')
DebugFlag('RubyVOQ_RC')

SimObject('GarnetLink_d.py')
SimObject('GarnetNetwork_d.py')
SimObject('GarnetRouter_d.py')
#if env['USE_PNET'] == 'True':
SimObject('GarnetRouter_PNET_Container_d.py')
SimObject('GarnetLink_PNET_Container_d.py')
Source('GarnetLink_PNET_Container_d.cc')

Source('GarnetLink_d.cc')
Source('GarnetNetwork_d.cc')
Source('InputUnit_d.cc')
Source('NetworkInterface_d.cc')
Source('Compressor_d.cc')
Source('Decompressor_d.cc')
Source('NetworkLink_d.cc')
Source('OutVcState_d.cc')
Source('OutputUnit_d.cc')
Source('Router_d.cc')
Source('RoutingUnit_d.cc')
Source('SWallocator_d.cc')
Source('Switch_d.cc')
Source('VCallocator_d.cc')
Source('VirtualChannel_d.cc')
Source('flitBuffer_d.cc')
Source('flit_d.cc')
Source('Resynchronizer.cc')
Source('DVFSPolicy.cpp')
Source('DVFSPolicyPNET.cc')
Source('PowerGatingPolicy.cc')

Source ('RoutingUnit_VOQ_d.cc')
Source ('VCallocator_VOQ_d.cc')

Source ('RoutingUnit_ADAPTIVE_d.cc')
Source ('VCallocator_ADAPTIVE_d.cc')
#if env['USE_PNET'] == 'True':
Source ('NetworkInterface_PNET_Container_d.cc')
Source ('NetworkLink_PNET_Container_d.cc')
Source ('Router_PNET_Container_d.cc')
